### PR TITLE
React-Setup

### PR DESCRIPTION
**Pull request by Mujeeb4582**
## Task completed
- Add the React-setup
- Add the linters setup

### CODE REVIEW

**Comment by Gopxfs** [comment]
# STATUS: INVALID REQUEST

Hi @Mujeeb4582 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project that doesn't contain a proper README file

Your Code Review Request will be marked invalid in your Dashboard, so please submit a new one once ready 🙏.
Invalid requests don't count as a review, so don't worry about that 😄!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Santiago220991 — APPROVED** [review]
Hi @Mujeeb4582, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highghts
:heavy_check_mark: Applied changes suggested by the last reviewer.
:heavy_check_mark: Followed Gitflow.
:heavy_check_mark: No linter errors.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Mujeeb4582** [comment]
@Santiago220991 its time to merge or can I make some changes because your are saying "There are some issues that you still need to work on to go to the next project but you are almost there!"
I don't understand it what you are saying?

**Comment by Santiago220991** [comment]
@Mujeeb4582 You can merge it right now. It is my mistake sorry for that. I already approved your project.

**Pull request merged**
